name: Run
on:
  workflow_dispatch:
  schedule:
    # run at 18 minutes past each hour
    - cron: '18 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: ruby run.rb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
